version: "3.4"

services:
  gogettingstarted:
    image: gogettingstarted
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8082:8080
    environment:
      - PORT=8080
